### ISSUE TITLE
Option to reopen 'closed' collections

### ISSUE THREAD

**Issue by gabi-gabs** [HumanRightsWatch/VHS#37]
Hi Esther, 

I accidentally closed someone's collection - could there be an option to 'reopen' closed collections/ and also to 'unarchive' them? 

Thanks,
Gabi

**Comment by U039b** [comment]
It is not possible to *unarchive* a collection since archiving a collection deletes all download files.

**Comment by U039b** [comment]
Should have been automatically deployed. @gabi-gabs do you confirm?

**Comment by gabi-gabs** [comment]
I couldn't see on VHS where I could reopen the batch. I just created a test where I archived a Collection but couldn't see an open to reopen it.

**Comment by U039b** [comment]
Ooops, I did a mistake. Collection actions are now hidden if the collection is closed. That's a bug.
Anyway, it will not be possible to reopen an archived collection. Closed collection only can be reopen.

**Comment by gabi-gabs** [comment]
Thank you for this, for archived collections - when users click on this, could they receive a warning message that says 'Warning: Once you archive this Collection, it is not possible to access it again or reopen it. Are you sure you want to archive this Collection? - And then ask users to click 'Yes' or 'No' and Yes - archives the Collection and No takes them out of this window. 

If users archive a collection, is it possible for Admin's to access these collections?

**Comment by U039b** [comment]
I will add a pop-in explaining the consequences and confirmation/cancel buttons. 
Based on the initial expression of your needs, you wanted to have the ability to *take care* of the storage space. That's why we introduced the possibility to archive a collection - remove all downloaded content without removing metadata for traceability purpose.

Even if a collection has been archived, anyone having access to it (owner, contributors, admins) can see it and the requested URL, metadata of the downloaded content, etc. But the downloaded content has been deleted from the storage. 
![image](https://user-images.githubusercontent.com/34188010/169272735-75ab0d62-633d-4874-b238-0fe935964d78.png)
![image](https://user-images.githubusercontent.com/34188010/169273474-7ca1c093-59d6-49df-98b2-4c0ee5d49112.png)

**Comment by gabi-gabs** [comment]
Thank you for more info on this. From what I understand from later conversations with James and Abir, we have a lot of storage and are not concerned about costs right now. I think the greater risk is colleagues accidentally archiving their Collections either by mistake or regretting it in the future and losing important content. Could we remove completely the option that staff delete content completely from storage? And if in the future it has become a nightmare then we reintroduce the idea?

**Comment by U039b** [comment]
Okay, I will remove the "Archive" button :)

**Comment by U039b** [comment]
Sould be fixed now.
